/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpraticoid.Graphic;

import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import net.sf.saxon.trans.XPathException;
import tpraticoid.Webpage1acesso;
import tpraticoid.Webpage2acessos;
import tpraticoid.XMLmaker;
import static tpraticoid.XMLmaker.xmlMunicipios;
import static tpraticoid.XMLmaker.xmlnoticias;
import tpraticoid.XMLtoArrays;
import static tpraticoid.XMLtoArrays.*;
import tpraticoid.XqueryFunctions;
import tpraticoid.municipio;
import tpraticoid.noticia;

/**
 *
 * @author Brums
 */
public class MainScreen extends javax.swing.JFrame {

    //Variaveis globais para poder usar os dados em todas as  interfaces
    public String data_glob;
    public ArrayList<noticia> NoticiasPesqAutor_Tipo = new ArrayList<>();
    public ArrayList<municipio> MunicipioPesqAutor_Tipo = new ArrayList<>();
    public String[] top5 = new String[10];
    
    /**
     * Creates new form MainScreen
     * @throws java.io.IOException
     */
    public MainScreen() throws IOException {
        initComponents();
        
        //Meter nao visivel todas as layers que nao queremos no inicio do programa
        lblInv.setVisible(false);
        Pnl2PesqAvancNoticias.setVisible(false);
        Pnl3PesqNoticias_Autor_e_Tipo.setVisible(false);
        Pnl2PesqAvancCamaras.setVisible(false);
        Pnl3PesqCamara_Show.setVisible(false);
        BarSeach.setVisible(false);
        Pnl3Pesq_top5_maisNoticias.setVisible(false);
        
        LbAutorPesq_noResult.setVisible(false);
        LbTipoPesq_noResult.setVisible(false);
        pesqCam_NoResult.setVisible(false);
        pesqCamPresidente_NoResult.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl1Data = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn_submitData = new javax.swing.JButton();
        dropdia = new javax.swing.JComboBox<>();
        dropmes = new javax.swing.JComboBox<>();
        lblInv = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Pnl2PesqAvancNoticias = new javax.swing.JPanel();
        Txt2 = new javax.swing.JLabel();
        Bnt_voltaData = new javax.swing.JButton();
        JfShowData_Not = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Txt_AutorNoticia = new javax.swing.JTextField();
        Txt_TipoNoticia = new javax.swing.JTextField();
        BtnPesqAutorNoticia = new javax.swing.JButton();
        BtnPesqTipoNoticia = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        LbAutorPesq_noResult = new javax.swing.JLabel();
        LbTipoPesq_noResult = new javax.swing.JLabel();
        Pnl3PesqNoticias_Autor_e_Tipo = new javax.swing.JPanel();
        NoticiasdoAutor_tipo = new javax.swing.JLabel();
        TxbAutor_Procurado = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TxbNumero_Noticia = new javax.swing.JLabel();
        TxbTipo_procAutor = new javax.swing.JLabel();
        TxbNumPublic_procAutor = new javax.swing.JLabel();
        TxbData_procAutor = new javax.swing.JLabel();
        TxbAutor_procAutor = new javax.swing.JLabel();
        BntNoticia_proxima = new javax.swing.JButton();
        BntNoticia_anterior = new javax.swing.JButton();
        TxbMax_Noticias = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxbLink_procAutor = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxbDescricao_procAutor = new javax.swing.JTextArea();
        BntPesqnoticias_voltar = new javax.swing.JButton();
        Pnl2PesqAvancCamaras = new javax.swing.JPanel();
        JfShowData_Cam = new javax.swing.JLabel();
        Txt3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_NomeCamara = new javax.swing.JTextField();
        BtnPesqCamNome = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        BtnPesqNomePresidCamara = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Txt_NomePresid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        BtnPesqtop5CamPublic = new javax.swing.JButton();
        Bnt_voltaData_cam = new javax.swing.JButton();
        pesqCam_NoResult = new javax.swing.JLabel();
        pesqCamPresidente_NoResult = new javax.swing.JLabel();
        Pnl3PesqCamara_Show = new javax.swing.JPanel();
        Txbmunicipio_brasao = new javax.swing.JLabel();
        BtnVoltar_municipio = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Txbmunicipio_nome = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Txbmunicipio_presidente = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Txbmunicipio_email = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Txbmunicipio_site = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Txbmunicipio_tel = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Txbmunicipio_numfreg = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Txbmunicipio_habitante = new javax.swing.JLabel();
        Txbmunicipio_area = new javax.swing.JLabel();
        Bnt_munic_proximo = new javax.swing.JButton();
        Bnt_munic_anterior = new javax.swing.JButton();
        Num_munic = new javax.swing.JLabel();
        max_num_munic = new javax.swing.JLabel();
        Pnl3Pesq_top5_maisNoticias = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        JfShowData_top5 = new javax.swing.JLabel();
        nomeNot_top1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nomeNot_top2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nomeNot_top3 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        nomeNot_top4 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        nomeNot_top5 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        numNot_top1 = new javax.swing.JLabel();
        numNot_top2 = new javax.swing.JLabel();
        numNot_top3 = new javax.swing.JLabel();
        numNot_top4 = new javax.swing.JLabel();
        numNot_top5 = new javax.swing.JLabel();
        Bntvoltar_top5 = new javax.swing.JButton();
        BarSeach = new javax.swing.JMenuBar();
        Menu_Pesq = new javax.swing.JMenu();
        MenuPesq_Op1 = new javax.swing.JMenuItem();
        MenuPesq_Op2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pnl1Data.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Introduza a data para pesquisas avançadas");

        Btn_submitData.setText("Enviar");
        Btn_submitData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_submitDataActionPerformed(evt);
            }
        });

        dropdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dropdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdiaActionPerformed(evt);
            }
        });

        dropmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        lblInv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInv.setForeground(new java.awt.Color(255, 0, 0));
        lblInv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInv.setText("Data invalida");
        lblInv.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblInv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("2107");

        jLabel3.setText("/");

        jLabel4.setText("/");

        javax.swing.GroupLayout Pnl1DataLayout = new javax.swing.GroupLayout(Pnl1Data);
        Pnl1Data.setLayout(Pnl1DataLayout);
        Pnl1DataLayout.setHorizontalGroup(
            Pnl1DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl1DataLayout.createSequentialGroup()
                .addGroup(Pnl1DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl1DataLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(dropdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(dropmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(Pnl1DataLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(Btn_submitData)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl1DataLayout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(Pnl1DataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pnl1DataLayout.setVerticalGroup(
            Pnl1DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl1DataLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl1DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(lblInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_submitData)
                .addGap(39, 39, 39))
        );

        dropdia.getAccessibleContext().setAccessibleName("");
        lblInv.getAccessibleContext().setAccessibleName("lblInval");

        Txt2.setText("Data:");

        Bnt_voltaData.setText("Voltar");
        Bnt_voltaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_voltaDataActionPerformed(evt);
            }
        });

        JfShowData_Not.setText("jLabel7");

        jLabel5.setText("Autor da Noticia:");

        jLabel6.setText("Tipo de Noticia:");

        Txt_AutorNoticia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_AutorNoticiaActionPerformed(evt);
            }
        });

        BtnPesqAutorNoticia.setText("Pesquisar");
        BtnPesqAutorNoticia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesqAutorNoticiaActionPerformed(evt);
            }
        });

        BtnPesqTipoNoticia.setText("Pesquisar");
        BtnPesqTipoNoticia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesqTipoNoticiaActionPerformed(evt);
            }
        });

        LbAutorPesq_noResult.setForeground(new java.awt.Color(255, 0, 0));
        LbAutorPesq_noResult.setText("Sem resultados");

        LbTipoPesq_noResult.setForeground(new java.awt.Color(255, 0, 0));
        LbTipoPesq_noResult.setText("Sem resultados");

        javax.swing.GroupLayout Pnl2PesqAvancNoticiasLayout = new javax.swing.GroupLayout(Pnl2PesqAvancNoticias);
        Pnl2PesqAvancNoticias.setLayout(Pnl2PesqAvancNoticiasLayout);
        Pnl2PesqAvancNoticiasLayout.setHorizontalGroup(
            Pnl2PesqAvancNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl2PesqAvancNoticiasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl2PesqAvancNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl2PesqAvancNoticiasLayout.createSequentialGroup()
                        .addGap(0, 265, Short.MAX_VALUE)
                        .addGroup(Pnl2PesqAvancNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bnt_voltaData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl2PesqAvancNoticiasLayout.createSequentialGroup()
                                .addComponent(Txt2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JfShowData_Not, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Pnl2PesqAvancNoticiasLayout.createSequentialGroup()
                        .addGroup(Pnl2PesqAvancNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Pnl2PesqAvancNoticiasLayout.createSequentialGroup()
                                .addGroup(Pnl2PesqAvancNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(Pnl2PesqAvancNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addGroup(Pnl2PesqAvancNoticiasLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(Pnl2PesqAvancNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LbTipoPesq_noResult)
                                                .addComponent(Txt_TipoNoticia, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(Pnl2PesqAvancNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LbAutorPesq_noResult)
                                        .addComponent(Txt_AutorNoticia, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(Pnl2PesqAvancNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnPesqTipoNoticia)
                                    .addComponent(BtnPesqAutorNoticia))
                                .addGap(68, 68, 68))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        Pnl2PesqAvancNoticiasLayout.setVerticalGroup(
            Pnl2PesqAvancNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl2PesqAvancNoticiasLayout.createSequentialGroup()
                .addGroup(Pnl2PesqAvancNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt2)
                    .addComponent(JfShowData_Not))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl2PesqAvancNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_AutorNoticia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPesqAutorNoticia))
                .addGap(12, 12, 12)
                .addComponent(LbAutorPesq_noResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl2PesqAvancNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_TipoNoticia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPesqTipoNoticia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LbTipoPesq_noResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Bnt_voltaData))
        );

        NoticiasdoAutor_tipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NoticiasdoAutor_tipo.setText("Pesquisa por:");

        TxbAutor_Procurado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxbAutor_Procurado.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Tipo:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Número de publicação:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Data:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Autor:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Descrição:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Link da Noticia:");

        TxbNumero_Noticia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TxbNumero_Noticia.setText("jLabel18");

        TxbTipo_procAutor.setText("jLabel18");

        TxbNumPublic_procAutor.setText("jLabel19");

        TxbData_procAutor.setText("jLabel20");

        TxbAutor_procAutor.setText("jLabel21");

        BntNoticia_proxima.setText("Proxima");
        BntNoticia_proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntNoticia_proximaActionPerformed(evt);
            }
        });

        BntNoticia_anterior.setText("Anterior");
        BntNoticia_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntNoticia_anteriorActionPerformed(evt);
            }
        });

        TxbMax_Noticias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxbMax_Noticias.setText("/ 3");

        TxbLink_procAutor.setColumns(20);
        TxbLink_procAutor.setRows(5);
        jScrollPane1.setViewportView(TxbLink_procAutor);

        TxbDescricao_procAutor.setColumns(20);
        TxbDescricao_procAutor.setRows(5);
        jScrollPane2.setViewportView(TxbDescricao_procAutor);

        BntPesqnoticias_voltar.setText("Voltar");
        BntPesqnoticias_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntPesqnoticias_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl3PesqNoticias_Autor_e_TipoLayout = new javax.swing.GroupLayout(Pnl3PesqNoticias_Autor_e_Tipo);
        Pnl3PesqNoticias_Autor_e_Tipo.setLayout(Pnl3PesqNoticias_Autor_e_TipoLayout);
        Pnl3PesqNoticias_Autor_e_TipoLayout.setHorizontalGroup(
            Pnl3PesqNoticias_Autor_e_TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createSequentialGroup()
                        .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxbTipo_procAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxbNumPublic_procAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxbData_procAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl3PesqNoticias_Autor_e_TipoLayout.createSequentialGroup()
                                .addComponent(NoticiasdoAutor_tipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxbAutor_Procurado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BntNoticia_anterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BntNoticia_proxima)
                                .addGap(12, 12, 12))
                            .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxbAutor_procAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createSequentialGroup()
                                .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl3PesqNoticias_Autor_e_TipoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BntPesqnoticias_voltar)))
                        .addContainerGap())
                    .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createSequentialGroup()
                        .addGap(10, 243, Short.MAX_VALUE)
                        .addComponent(TxbNumero_Noticia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxbMax_Noticias)
                        .addGap(80, 80, 80))))
        );
        Pnl3PesqNoticias_Autor_e_TipoLayout.setVerticalGroup(
            Pnl3PesqNoticias_Autor_e_TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoticiasdoAutor_tipo)
                    .addComponent(BntNoticia_proxima)
                    .addComponent(BntNoticia_anterior)
                    .addComponent(TxbAutor_Procurado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxbNumero_Noticia)
                    .addComponent(TxbMax_Noticias))
                .addGap(20, 20, 20)
                .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TxbTipo_procAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TxbNumPublic_procAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxbData_procAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl3PesqNoticias_Autor_e_TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TxbAutor_procAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(BntPesqnoticias_voltar)
                .addContainerGap())
        );

        JfShowData_Cam.setText("jLabel7");

        Txt3.setText("Data:");

        jLabel7.setText("Câmara de:");

        BtnPesqCamNome.setText("Pesquisar");
        BtnPesqCamNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesqCamNomeActionPerformed(evt);
            }
        });

        BtnPesqNomePresidCamara.setText("Pesquisar");
        BtnPesqNomePresidCamara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesqNomePresidCamaraActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome do Presidente da Câmara:");

        jLabel9.setText("Top5 - Câmaras com mais publicações");

        BtnPesqtop5CamPublic.setText("Pesquisar");
        BtnPesqtop5CamPublic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesqtop5CamPublicActionPerformed(evt);
            }
        });

        Bnt_voltaData_cam.setText("Voltar");
        Bnt_voltaData_cam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_voltaData_camActionPerformed(evt);
            }
        });

        pesqCam_NoResult.setForeground(new java.awt.Color(255, 51, 51));
        pesqCam_NoResult.setText("Sem resultados");

        pesqCamPresidente_NoResult.setForeground(new java.awt.Color(255, 51, 51));
        pesqCamPresidente_NoResult.setText("Sem resultados");

        javax.swing.GroupLayout Pnl2PesqAvancCamarasLayout = new javax.swing.GroupLayout(Pnl2PesqAvancCamaras);
        Pnl2PesqAvancCamaras.setLayout(Pnl2PesqAvancCamarasLayout);
        Pnl2PesqAvancCamarasLayout.setHorizontalGroup(
            Pnl2PesqAvancCamarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl2PesqAvancCamarasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Pnl2PesqAvancCamarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl2PesqAvancCamarasLayout.createSequentialGroup()
                        .addComponent(Txt3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JfShowData_Cam, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Bnt_voltaData_cam, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(Pnl2PesqAvancCamarasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl2PesqAvancCamarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pnl2PesqAvancCamarasLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(Pnl2PesqAvancCamarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl2PesqAvancCamarasLayout.createSequentialGroup()
                                .addComponent(pesqCam_NoResult)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Pnl2PesqAvancCamarasLayout.createSequentialGroup()
                                .addComponent(txt_NomeCamara, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(BtnPesqCamNome)
                                .addGap(39, 39, 39))))
                    .addGroup(Pnl2PesqAvancCamarasLayout.createSequentialGroup()
                        .addGroup(Pnl2PesqAvancCamarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(Pnl2PesqAvancCamarasLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(Pnl2PesqAvancCamarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Pnl2PesqAvancCamarasLayout.createSequentialGroup()
                                        .addComponent(pesqCamPresidente_NoResult)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(Pnl2PesqAvancCamarasLayout.createSequentialGroup()
                                        .addComponent(Txt_NomePresid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnPesqNomePresidCamara)
                                        .addGap(27, 27, 27))))
                            .addGroup(Pnl2PesqAvancCamarasLayout.createSequentialGroup()
                                .addGroup(Pnl2PesqAvancCamarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addGroup(Pnl2PesqAvancCamarasLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel9)
                                        .addGap(28, 28, 28)
                                        .addComponent(BtnPesqtop5CamPublic)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        Pnl2PesqAvancCamarasLayout.setVerticalGroup(
            Pnl2PesqAvancCamarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl2PesqAvancCamarasLayout.createSequentialGroup()
                .addGroup(Pnl2PesqAvancCamarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt3)
                    .addComponent(JfShowData_Cam))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl2PesqAvancCamarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NomeCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPesqCamNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pesqCam_NoResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl2PesqAvancCamarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_NomePresid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPesqNomePresidCamara))
                .addGap(7, 7, 7)
                .addComponent(pesqCamPresidente_NoResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Pnl2PesqAvancCamarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(BtnPesqtop5CamPublic))
                .addGap(18, 18, 18)
                .addComponent(Bnt_voltaData_cam))
        );

        Txbmunicipio_brasao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txbmunicipio_brasao.setText("brasao");

        BtnVoltar_municipio.setText("Voltar");
        BtnVoltar_municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltar_municipioActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Municipio de:");

        Txbmunicipio_nome.setText("jLabel11");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Presidente:");

        Txbmunicipio_presidente.setText("jLabel19");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("E-mail:");

        Txbmunicipio_email.setText("jLabel21");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Web-site:");

        Txbmunicipio_site.setText("jLabel23");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Telefone:");

        Txbmunicipio_tel.setText("jLabel25");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Numero de Freguesias:");

        Txbmunicipio_numfreg.setText("jLabel27");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Area do municipio:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Habitantes:");

        Txbmunicipio_habitante.setText("jLabel30");

        Txbmunicipio_area.setText("jLabel31");

        Bnt_munic_proximo.setText(">");
        Bnt_munic_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_munic_proximoActionPerformed(evt);
            }
        });

        Bnt_munic_anterior.setText("<");
        Bnt_munic_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_munic_anteriorActionPerformed(evt);
            }
        });

        Num_munic.setText("1");

        max_num_munic.setText("/ 1");

        javax.swing.GroupLayout Pnl3PesqCamara_ShowLayout = new javax.swing.GroupLayout(Pnl3PesqCamara_Show);
        Pnl3PesqCamara_Show.setLayout(Pnl3PesqCamara_ShowLayout);
        Pnl3PesqCamara_ShowLayout.setHorizontalGroup(
            Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txbmunicipio_nome))
                    .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                        .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txbmunicipio_numfreg))
                            .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txbmunicipio_area))
                            .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txbmunicipio_habitante))
                            .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txbmunicipio_tel))
                            .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txbmunicipio_presidente))
                            .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txbmunicipio_email))
                            .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txbmunicipio_site)))
                        .addGap(35, 35, 35)
                        .addComponent(Txbmunicipio_brasao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Num_munic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(max_num_munic))
                    .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                        .addComponent(Bnt_munic_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bnt_munic_proximo)
                        .addGap(54, 54, 54)
                        .addComponent(BtnVoltar_municipio)))
                .addGap(69, 69, 69))
        );
        Pnl3PesqCamara_ShowLayout.setVerticalGroup(
            Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Txbmunicipio_nome))
                .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Txbmunicipio_presidente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(Txbmunicipio_email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(Txbmunicipio_site))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(Txbmunicipio_tel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txbmunicipio_numfreg)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(Txbmunicipio_area))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(Txbmunicipio_habitante)))
                    .addGroup(Pnl3PesqCamara_ShowLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Txbmunicipio_brasao, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num_munic)
                    .addComponent(max_num_munic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl3PesqCamara_ShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bnt_munic_proximo)
                    .addComponent(Bnt_munic_anterior)
                    .addComponent(BtnVoltar_municipio))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Os 5 Municipios com mais noticias no dia:");

        JfShowData_top5.setText("jLabel19");

        nomeNot_top1.setText("jLabel19");

        jLabel21.setText("Numero de Noticias publicadas:");

        nomeNot_top2.setText("jLabel23");

        jLabel25.setText("Numero de Noticias publicadas:");

        nomeNot_top3.setText("jLabel23");

        jLabel30.setText("Numero de Noticias publicadas:");

        nomeNot_top4.setText("jLabel23");

        jLabel32.setText("Numero de Noticias publicadas:");

        nomeNot_top5.setText("jLabel23");

        jLabel34.setText("Numero de Noticias publicadas:");

        numNot_top1.setText("jLabel35");

        numNot_top2.setText("jLabel36");

        numNot_top3.setText("jLabel37");

        numNot_top4.setText("jLabel38");

        numNot_top5.setText("jLabel39");

        Bntvoltar_top5.setText("voltar");
        Bntvoltar_top5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bntvoltar_top5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl3Pesq_top5_maisNoticiasLayout = new javax.swing.GroupLayout(Pnl3Pesq_top5_maisNoticias);
        Pnl3Pesq_top5_maisNoticias.setLayout(Pnl3Pesq_top5_maisNoticiasLayout);
        Pnl3Pesq_top5_maisNoticiasLayout.setHorizontalGroup(
            Pnl3Pesq_top5_maisNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numNot_top5))
                    .addComponent(nomeNot_top5)
                    .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numNot_top4))
                    .addComponent(nomeNot_top4)
                    .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numNot_top3))
                    .addComponent(nomeNot_top3)
                    .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numNot_top2))
                    .addComponent(nomeNot_top2)
                    .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numNot_top1))
                    .addComponent(nomeNot_top1)
                    .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JfShowData_top5)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl3Pesq_top5_maisNoticiasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bntvoltar_top5)
                .addContainerGap())
        );
        Pnl3Pesq_top5_maisNoticiasLayout.setVerticalGroup(
            Pnl3Pesq_top5_maisNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JfShowData_top5))
                .addGap(18, 18, 18)
                .addComponent(nomeNot_top1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(numNot_top1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeNot_top2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(numNot_top2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeNot_top3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(numNot_top3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeNot_top4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(numNot_top4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeNot_top5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl3Pesq_top5_maisNoticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(numNot_top5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Bntvoltar_top5)
                .addContainerGap())
        );

        Menu_Pesq.setText("Pesquisar por");

        MenuPesq_Op1.setText("Noticias");
        MenuPesq_Op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPesq_Op1ActionPerformed(evt);
            }
        });
        Menu_Pesq.add(MenuPesq_Op1);

        MenuPesq_Op2.setText("Câmaras");
        MenuPesq_Op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPesq_Op2ActionPerformed(evt);
            }
        });
        Menu_Pesq.add(MenuPesq_Op2);

        BarSeach.add(Menu_Pesq);

        setJMenuBar(BarSeach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pnl3PesqNoticias_Autor_e_Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl2PesqAvancNoticias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl1Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl2PesqAvancCamaras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl3PesqCamara_Show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl3Pesq_top5_maisNoticias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pnl3PesqNoticias_Autor_e_Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl2PesqAvancNoticias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl1Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl2PesqAvancCamaras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl3PesqCamara_Show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl3Pesq_top5_maisNoticias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdiaActionPerformed

    private void Btn_submitDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_submitDataActionPerformed

        int dia = dropdia.getSelectedIndex();
        int mes = dropmes.getSelectedIndex();

        if(dia == 0 || mes == 0){
            lblInv.setVisible(true);
            lblInv.setText("Data Invalida");
        }
        else{
            if((mes == 2 && dia == 30) || (mes == 2 && dia == 31)){
                lblInv.setVisible(true);
                lblInv.setText("Data Invalida");
            }
            else
            {
                if(mes == 4 || mes == 6 || mes == 9 || mes == 11 && dia == 31){
                    lblInv.setVisible(true);
                    lblInv.setText("Data Invalida");
                }
                else
                {
                    String data  = "2017-" + mes + "-" + dia;
                    data_glob = data;
                    try {
                        prog(data);
                    } catch (IOException ex) {
                        Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_Btn_submitDataActionPerformed

    private void Bnt_voltaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_voltaDataActionPerformed
        // TODO add your handling code here:
        
        Pnl2PesqAvancNoticias.setVisible(false);
        Pnl2PesqAvancCamaras.setVisible(false);
        BarSeach.setVisible(false);
        Pnl1Data.setVisible(true);
        lblInv.setVisible(false);
        
    }//GEN-LAST:event_Bnt_voltaDataActionPerformed

    private void MenuPesq_Op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPesq_Op1ActionPerformed
        // TODO add your handling code here:
        Pnl2PesqAvancCamaras.setVisible(false);
        Pnl2PesqAvancNoticias.setVisible(true);
        JfShowData_Not.setText(data_glob);
    }//GEN-LAST:event_MenuPesq_Op1ActionPerformed

    private void BtnPesqtop5CamPublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesqtop5CamPublicActionPerformed
  
        try {
            //Cria uma lista ordenada dos municipios das noticias
            XqueryFunctions.xQueryToXml("pesqListaMunic.xml", "XQListaMunic.xql");
            
            //Conta e regista quantas noticias cada municipio tem
            XqueryFunctions.xQueryToXml("pesqListaMunic.xml", "XQListaMunicCount.xql");
            
            //Ordena os dados por ondem decrescente
            XqueryFunctions.xQueryToXml("pesqListaMunic.xml", "XQListaMunicCountDesc.xql");
            
            //Retira o top 5 dos municipios com mais noticias
            XqueryFunctions.xQueryToXml("pesqListaMunic.xml", "XQListaMunicCountDesc5.xql");
            
        } catch (XPathException | IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try {
            top5 = XmlPesqtop5();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(top5.length != 0){
            
            nomeNot_top1.setText(top5[0].trim());
            numNot_top1.setText(top5[1].trim());
            nomeNot_top2.setText(top5[2].trim());
            numNot_top2.setText(top5[3].trim());
            nomeNot_top3.setText(top5[4].trim());
            numNot_top3.setText(top5[5].trim());
            nomeNot_top4.setText(top5[6].trim());
            numNot_top4.setText(top5[7].trim());
            nomeNot_top5.setText(top5[8].trim());
            numNot_top5.setText(top5[9].trim());

            JfShowData_top5.setText(data_glob);
            
            Pnl2PesqAvancCamaras.setVisible(false);
            BarSeach.setVisible(false);
            Pnl3Pesq_top5_maisNoticias.setVisible(true);
        }
        
    }//GEN-LAST:event_BtnPesqtop5CamPublicActionPerformed

    private void MenuPesq_Op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPesq_Op2ActionPerformed
        // TODO add your handling code here:
        Pnl2PesqAvancCamaras.setVisible(true);
        Pnl2PesqAvancNoticias.setVisible(false);
        JfShowData_Cam.setText(data_glob);
        BarSeach.setVisible(true);
    }//GEN-LAST:event_MenuPesq_Op2ActionPerformed

    private void Bnt_voltaData_camActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_voltaData_camActionPerformed
        // TODO add your handling code here:
        Pnl2PesqAvancNoticias.setVisible(false);
        Pnl2PesqAvancCamaras.setVisible(false);
        BarSeach.setVisible(false);
        Pnl1Data.setVisible(true);
        lblInv.setVisible(false);
        
    }//GEN-LAST:event_Bnt_voltaData_camActionPerformed

    private void BtnPesqAutorNoticiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesqAutorNoticiaActionPerformed
        // TODO add your handling code here:
        NoticiasPesqAutor_Tipo.clear();
        String pesq = Txt_AutorNoticia.getText();
        pesq = capitalize(pesq);

        try {
            XMLmaker.xmlPesquisa(pesq);
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            XqueryFunctions.xQueryToXml("pesqAutor.xml", "XQAutor.xql");
        } catch (XPathException | IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            NoticiasPesqAutor_Tipo = XmlPesqNoticiasAutorToArray();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }  
        if(!NoticiasPesqAutor_Tipo.isEmpty()){
            TxbAutor_Procurado.setText(pesq);
            TxbTipo_procAutor.setText(NoticiasPesqAutor_Tipo.get(0).getTipo());
            TxbNumPublic_procAutor.setText(NoticiasPesqAutor_Tipo.get(0).getNumPub());
            TxbData_procAutor.setText(NoticiasPesqAutor_Tipo.get(0).getData());
            TxbAutor_procAutor.setText(NoticiasPesqAutor_Tipo.get(0).getAutor());
            TxbDescricao_procAutor.setText(NoticiasPesqAutor_Tipo.get(0).getDescricao());
            TxbLink_procAutor.setText(NoticiasPesqAutor_Tipo.get(0).getLink());
            TxbNumero_Noticia.setText("1");
            TxbMax_Noticias.setText("/ " + NoticiasPesqAutor_Tipo.size());
            NoticiasdoAutor_tipo.setText("Noticias do Autor:");

            Pnl2PesqAvancNoticias.setVisible(false);
            BarSeach.setVisible(false);
            Pnl3PesqNoticias_Autor_e_Tipo.setVisible(true);
        }
        else
            LbAutorPesq_noResult.setVisible(true);
    }//GEN-LAST:event_BtnPesqAutorNoticiaActionPerformed

    private void Txt_AutorNoticiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_AutorNoticiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_AutorNoticiaActionPerformed

    private void BntNoticia_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntNoticia_anteriorActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(TxbNumero_Noticia.getText());
        
        if(num != 1)
        {
            TxbTipo_procAutor.setText(NoticiasPesqAutor_Tipo.get(num-2).getTipo());
            TxbNumPublic_procAutor.setText(NoticiasPesqAutor_Tipo.get(num-2).getNumPub());
            TxbData_procAutor.setText(NoticiasPesqAutor_Tipo.get(num-2).getData());
            TxbAutor_procAutor.setText(NoticiasPesqAutor_Tipo.get(num-2).getAutor());
            TxbDescricao_procAutor.setText(NoticiasPesqAutor_Tipo.get(num-2).getDescricao());
            TxbLink_procAutor.setText(NoticiasPesqAutor_Tipo.get(num-2).getLink());
            TxbNumero_Noticia.setText(num-1+"");
        }
        
    }//GEN-LAST:event_BntNoticia_anteriorActionPerformed

    private void BntNoticia_proximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntNoticia_proximaActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(TxbNumero_Noticia.getText());
        
        if(num != NoticiasPesqAutor_Tipo.size())
        {
            TxbTipo_procAutor.setText(NoticiasPesqAutor_Tipo.get(num).getTipo());
            TxbNumPublic_procAutor.setText(NoticiasPesqAutor_Tipo.get(num).getNumPub());
            TxbData_procAutor.setText(NoticiasPesqAutor_Tipo.get(num).getData());
            TxbAutor_procAutor.setText(NoticiasPesqAutor_Tipo.get(num).getAutor());
            TxbDescricao_procAutor.setText(NoticiasPesqAutor_Tipo.get(num).getDescricao());
            TxbLink_procAutor.setText(NoticiasPesqAutor_Tipo.get(num).getLink());
            TxbNumero_Noticia.setText(num+1+"");
        }
        
    }//GEN-LAST:event_BntNoticia_proximaActionPerformed

    private void BtnPesqTipoNoticiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesqTipoNoticiaActionPerformed
        // TODO add your handling code here:
        NoticiasPesqAutor_Tipo.clear();
        String pesq = Txt_TipoNoticia.getText();
        pesq = capitalize(pesq);

        try {
            XMLmaker.xmlPesquisa(pesq);
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            XqueryFunctions.xQueryToXml("pesqTipo.xml", "XQTipo.xql");
        } catch (XPathException | IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            NoticiasPesqAutor_Tipo = XMLtoArrays.XmlPesqNoticiasTipoToArray();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }  
        if(!NoticiasPesqAutor_Tipo.isEmpty()){
            TxbAutor_Procurado.setText(pesq);
            TxbTipo_procAutor.setText(NoticiasPesqAutor_Tipo.get(0).getTipo());
            TxbNumPublic_procAutor.setText(NoticiasPesqAutor_Tipo.get(0).getNumPub());
            TxbData_procAutor.setText(NoticiasPesqAutor_Tipo.get(0).getData());
            TxbAutor_procAutor.setText(NoticiasPesqAutor_Tipo.get(0).getAutor());
            TxbDescricao_procAutor.setText(NoticiasPesqAutor_Tipo.get(0).getDescricao());
            TxbLink_procAutor.setText(NoticiasPesqAutor_Tipo.get(0).getLink());
            TxbNumero_Noticia.setText("1");
            TxbMax_Noticias.setText("/ " + NoticiasPesqAutor_Tipo.size());
            NoticiasdoAutor_tipo.setText("Noticias do Tipo:");

            Pnl2PesqAvancNoticias.setVisible(false);
            BarSeach.setVisible(false);
            Pnl3PesqNoticias_Autor_e_Tipo.setVisible(true);
        }
        else
            LbTipoPesq_noResult.setVisible(true);
    }//GEN-LAST:event_BtnPesqTipoNoticiaActionPerformed

    private void BntPesqnoticias_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntPesqnoticias_voltarActionPerformed
        // TODO add your handling code here:
        
        Pnl2PesqAvancNoticias.setVisible(true);
        BarSeach.setVisible(true);
        Pnl3PesqNoticias_Autor_e_Tipo.setVisible(false);
        LbAutorPesq_noResult.setVisible(false);
        LbTipoPesq_noResult.setVisible(false);
        
    }//GEN-LAST:event_BntPesqnoticias_voltarActionPerformed

    private void BtnPesqCamNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesqCamNomeActionPerformed
        // TODO add your handling code here:
        
        MunicipioPesqAutor_Tipo.clear();
        String pesq = txt_NomeCamara.getText();
        pesq = capitalize(pesq);

        try {
            XMLmaker.xmlPesquisa(pesq);
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            XqueryFunctions.xQueryToXml("pesqcamara.xml", "XQCamara.xql");
        } catch (XPathException | IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            MunicipioPesqAutor_Tipo = XMLtoArrays.XmlPesqMunicipioToArray();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }  
        if(!MunicipioPesqAutor_Tipo.isEmpty()){
            Txbmunicipio_nome.setText(MunicipioPesqAutor_Tipo.get(0).getNomeMunicipio());
            Txbmunicipio_presidente.setText(MunicipioPesqAutor_Tipo.get(0).getPresidenteCamara());
            Txbmunicipio_email.setText(MunicipioPesqAutor_Tipo.get(0).getMail());
            Txbmunicipio_site.setText(MunicipioPesqAutor_Tipo.get(0).getWebSite());
            Txbmunicipio_tel.setText(MunicipioPesqAutor_Tipo.get(0).getTelefone());
            Txbmunicipio_numfreg.setText(MunicipioPesqAutor_Tipo.get(0).getNumFreguesias());
            Txbmunicipio_area.setText(MunicipioPesqAutor_Tipo.get(0).getKm2());
            Txbmunicipio_habitante.setText(MunicipioPesqAutor_Tipo.get(0).getHabitantes());
            
            String linkIMG = MunicipioPesqAutor_Tipo.get(0).getImagem();
            
            URL url = null;
            try {
                url = new URL(linkIMG);
            } catch (MalformedURLException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            Image image = null;
            try {
                image = ImageIO.read(url);
            } catch (IOException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            image = image.getScaledInstance(130, 145, 2);
            Txbmunicipio_brasao.setText("");
            
            Txbmunicipio_brasao.setIcon(new ImageIcon(image));
            
            Num_munic.setText("1");
            max_num_munic.setText("/ " + MunicipioPesqAutor_Tipo.size());

            Pnl2PesqAvancCamaras.setVisible(false);
            BarSeach.setVisible(false);
            Pnl3PesqCamara_Show.setVisible(true);
        }
        else
            pesqCam_NoResult.setVisible(true);
        
    }//GEN-LAST:event_BtnPesqCamNomeActionPerformed

    private void Bnt_munic_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_munic_anteriorActionPerformed
        // TODO add your handling code here:
        
        int num = Integer.parseInt(Num_munic.getText());
        
        if(num != 1)
        {
            Txbmunicipio_nome.setText(MunicipioPesqAutor_Tipo.get(num-2).getNomeMunicipio());
            Txbmunicipio_presidente.setText(MunicipioPesqAutor_Tipo.get(num-2).getPresidenteCamara());
            Txbmunicipio_email.setText(MunicipioPesqAutor_Tipo.get(num-2).getMail());
            Txbmunicipio_site.setText(MunicipioPesqAutor_Tipo.get(num-2).getWebSite());
            Txbmunicipio_tel.setText(MunicipioPesqAutor_Tipo.get(num-2).getTelefone());
            Txbmunicipio_numfreg.setText(MunicipioPesqAutor_Tipo.get(num-2).getNumFreguesias());
            Txbmunicipio_area.setText(MunicipioPesqAutor_Tipo.get(num-2).getKm2());
            Txbmunicipio_habitante.setText(MunicipioPesqAutor_Tipo.get(num-2).getHabitantes());
            
            String linkIMG = MunicipioPesqAutor_Tipo.get(num-2).getImagem();
            
            URL url = null;
            try {
                url = new URL(linkIMG);
            } catch (MalformedURLException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            Image image = null;
            try {
                image = ImageIO.read(url);
            } catch (IOException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            image = image.getScaledInstance(130, 145, 2);
            Txbmunicipio_brasao.setText("");
            
            Txbmunicipio_brasao.setIcon(new ImageIcon(image));
            
            Num_munic.setText(num - 1 +"");
            max_num_munic.setText("/ " + MunicipioPesqAutor_Tipo.size());
            
        }
        
    }//GEN-LAST:event_Bnt_munic_anteriorActionPerformed

    private void BtnVoltar_municipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltar_municipioActionPerformed
        // TODO add your handling code here:
        
        Pnl3PesqCamara_Show.setVisible(false);
        BarSeach.setVisible(true);
        Pnl2PesqAvancCamaras.setVisible(true);
        pesqCam_NoResult.setVisible(false);
        
    }//GEN-LAST:event_BtnVoltar_municipioActionPerformed

    private void Bnt_munic_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_munic_proximoActionPerformed
        // TODO add your handling code here:
        
        int num = Integer.parseInt(Num_munic.getText());
        
        if(num != MunicipioPesqAutor_Tipo.size())
        {
            Txbmunicipio_nome.setText(MunicipioPesqAutor_Tipo.get(num).getNomeMunicipio());
            Txbmunicipio_presidente.setText(MunicipioPesqAutor_Tipo.get(num).getPresidenteCamara());
            Txbmunicipio_email.setText(MunicipioPesqAutor_Tipo.get(num).getMail());
            Txbmunicipio_site.setText(MunicipioPesqAutor_Tipo.get(num).getWebSite());
            Txbmunicipio_tel.setText(MunicipioPesqAutor_Tipo.get(num).getTelefone());
            Txbmunicipio_numfreg.setText(MunicipioPesqAutor_Tipo.get(num).getNumFreguesias());
            Txbmunicipio_area.setText(MunicipioPesqAutor_Tipo.get(num).getKm2());
            Txbmunicipio_habitante.setText(MunicipioPesqAutor_Tipo.get(num).getHabitantes());
            
            String linkIMG = MunicipioPesqAutor_Tipo.get(num).getImagem();
            
            URL url = null;
            try {
                url = new URL(linkIMG);
            } catch (MalformedURLException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            Image image = null;
            try {
                image = ImageIO.read(url);
            } catch (IOException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            image = image.getScaledInstance(130, 145, 2);
            Txbmunicipio_brasao.setText("");
            
            Txbmunicipio_brasao.setIcon(new ImageIcon(image));
            
            Num_munic.setText(num + 1 +"");
            max_num_munic.setText("/ " + MunicipioPesqAutor_Tipo.size());
            
        }
        
    }//GEN-LAST:event_Bnt_munic_proximoActionPerformed

    private void BtnPesqNomePresidCamaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesqNomePresidCamaraActionPerformed
        // TODO add your handling code here:
        
        MunicipioPesqAutor_Tipo.clear();
        String pesq = Txt_NomePresid.getText();
        pesq = capitalize(pesq);

        try {
            XMLmaker.xmlPesquisa(pesq);
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            XqueryFunctions.xQueryToXml("pesqpresidente.xml", "XQPresidente.xql");
        } catch (XPathException | IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            MunicipioPesqAutor_Tipo = XMLtoArrays.XmlPesqPresidenteMunic_ToArray();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }  
        if(!MunicipioPesqAutor_Tipo.isEmpty()){
            Txbmunicipio_nome.setText(MunicipioPesqAutor_Tipo.get(0).getNomeMunicipio());
            Txbmunicipio_presidente.setText(MunicipioPesqAutor_Tipo.get(0).getPresidenteCamara());
            Txbmunicipio_email.setText(MunicipioPesqAutor_Tipo.get(0).getMail());
            Txbmunicipio_site.setText(MunicipioPesqAutor_Tipo.get(0).getWebSite());
            Txbmunicipio_tel.setText(MunicipioPesqAutor_Tipo.get(0).getTelefone());
            Txbmunicipio_numfreg.setText(MunicipioPesqAutor_Tipo.get(0).getNumFreguesias());
            Txbmunicipio_area.setText(MunicipioPesqAutor_Tipo.get(0).getKm2());
            Txbmunicipio_habitante.setText(MunicipioPesqAutor_Tipo.get(0).getHabitantes());
            
            String linkIMG = MunicipioPesqAutor_Tipo.get(0).getImagem();
            
            URL url = null;
            try {
                url = new URL(linkIMG);
            } catch (MalformedURLException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            Image image = null;
            try {
                image = ImageIO.read(url);
            } catch (IOException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            image = image.getScaledInstance(130, 145, 2);
            Txbmunicipio_brasao.setText("");
            
            Txbmunicipio_brasao.setIcon(new ImageIcon(image));
            
            Num_munic.setText("1");
            max_num_munic.setText("/ " + MunicipioPesqAutor_Tipo.size());

            Pnl2PesqAvancCamaras.setVisible(false);
            BarSeach.setVisible(false);
            Pnl3PesqCamara_Show.setVisible(true);
        }
        else
            pesqCam_NoResult.setVisible(true);
        
    }//GEN-LAST:event_BtnPesqNomePresidCamaraActionPerformed

    private void Bntvoltar_top5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bntvoltar_top5ActionPerformed
        // TODO add your handling code here:
        
        Pnl2PesqAvancNoticias.setVisible(true);
        BarSeach.setVisible(true);
        Pnl3Pesq_top5_maisNoticias.setVisible(false);
        
    }//GEN-LAST:event_Bntvoltar_top5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MainScreen().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
    
    public void prog(String data) throws IOException{
        
        //ArrayList para as noticias / primeiro site
        ArrayList<noticia> grupoNoticias = new ArrayList<>();
        //ArrayList para os municipios / segundo site
        ArrayList<municipio> grupoMunicipios = new ArrayList<>();
              
        //Vai buscar o ficheiro da pagina com a data dada
        Webpage1acesso.procurarNoticias(data);
        
        ArrayList<String> tipoNoticia = Webpage1acesso.procTipoPublic();
        //System.out.println(tipoNoticia.size());
        ArrayList<String> numNoticia = Webpage1acesso.procNumPublic();
        //System.out.println(numNoticia.size());
        ArrayList<String> dataNoticia = Webpage1acesso.procDataPublic();
        //System.out.println(dataNoticia.size());
        ArrayList<String> AutorNoticia = Webpage1acesso.procAutor();
        //System.out.println(AutorNoticia.size());
        ArrayList<String> DescricaoNoticia = Webpage1acesso.procDescricao();
        //System.out.println(DescricaoNoticia.size());
        ArrayList<String> LinkNoticia = Webpage1acesso.procLink();
        //System.out.println(LinkNoticia.size());
        
        //Criacao das noticias no arraylist com as informacoes
        for(int i=0;i<tipoNoticia.size();i++){ 
            noticia n1 = new noticia(tipoNoticia.get(i),numNoticia.get(i),dataNoticia.get(i),AutorNoticia.get(i),DescricaoNoticia.get(i),LinkNoticia.get(i));         
            grupoNoticias.add(n1);
        }     
        
        //Vai buscar a pagina que contem os codigos para consulta
        Webpage2acessos.ProcuraSite2();
        
        //Array com os nomes dos municipios ja arranjados
        ArrayList<String> nomesMunic = Webpage2acessos.retiraDuplicados(grupoNoticias);
        
        
        //for para criar os municipios
        for (int i = 0; i < nomesMunic.size(); i++) {
            
            //Retira o texto Municipio de da string e vai buscar o codigo do municipio
            Webpage2acessos.procPageMunicip(nomesMunic.get(i));
            
            //dados do municipio
            String Presidente = Webpage2acessos.procPresidenteCamara();          
            String mail = Webpage2acessos.procMail();
            String siteInst = Webpage2acessos.procSiteInst();
            String telefone = Webpage2acessos.procTelefone();
            String freg = Webpage2acessos.procFreg();
            String km = Webpage2acessos.prockm2();
            String habitantes = Webpage2acessos.procHabitante();
            String imagem = Webpage2acessos.procimagem();
            
            municipio municip= new municipio(nomesMunic.get(i), Presidente, mail, siteInst, telefone, freg, km, habitantes, imagem);
            
            grupoMunicipios.add(municip);
            
        } 
        
        //cria o xml das noticias
        xmlnoticias(grupoNoticias);
        xmlMunicipios(grupoMunicipios);
        
        /*Parte grafica depois da data ser introduzida*/
        
        pesqAvanc(data);
        
    }
    
    public void pesqAvanc(String data){
        
        Pnl1Data.setVisible(false);
        JfShowData_Not.setText(data);
        Pnl2PesqAvancNoticias.setVisible(true);
        JfShowData_Cam.setText(data);
        BarSeach.setVisible(true);
        
    }
    
    public String capitalize(String line) {
    return Character.toUpperCase(line.charAt(0)) + line.substring(1);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarSeach;
    private javax.swing.JButton BntNoticia_anterior;
    private javax.swing.JButton BntNoticia_proxima;
    private javax.swing.JButton BntPesqnoticias_voltar;
    private javax.swing.JButton Bnt_munic_anterior;
    private javax.swing.JButton Bnt_munic_proximo;
    private javax.swing.JButton Bnt_voltaData;
    private javax.swing.JButton Bnt_voltaData_cam;
    private javax.swing.JButton Bntvoltar_top5;
    private javax.swing.JButton BtnPesqAutorNoticia;
    private javax.swing.JButton BtnPesqCamNome;
    private javax.swing.JButton BtnPesqNomePresidCamara;
    private javax.swing.JButton BtnPesqTipoNoticia;
    private javax.swing.JButton BtnPesqtop5CamPublic;
    private javax.swing.JButton BtnVoltar_municipio;
    private javax.swing.JButton Btn_submitData;
    private javax.swing.JLabel JfShowData_Cam;
    private javax.swing.JLabel JfShowData_Not;
    private javax.swing.JLabel JfShowData_top5;
    private javax.swing.JLabel LbAutorPesq_noResult;
    private javax.swing.JLabel LbTipoPesq_noResult;
    private javax.swing.JMenuItem MenuPesq_Op1;
    private javax.swing.JMenuItem MenuPesq_Op2;
    private javax.swing.JMenu Menu_Pesq;
    private javax.swing.JLabel NoticiasdoAutor_tipo;
    private javax.swing.JLabel Num_munic;
    private javax.swing.JPanel Pnl1Data;
    private javax.swing.JPanel Pnl2PesqAvancCamaras;
    private javax.swing.JPanel Pnl2PesqAvancNoticias;
    private javax.swing.JPanel Pnl3PesqCamara_Show;
    private javax.swing.JPanel Pnl3PesqNoticias_Autor_e_Tipo;
    private javax.swing.JPanel Pnl3Pesq_top5_maisNoticias;
    private javax.swing.JLabel TxbAutor_Procurado;
    private javax.swing.JLabel TxbAutor_procAutor;
    private javax.swing.JLabel TxbData_procAutor;
    private javax.swing.JTextArea TxbDescricao_procAutor;
    private javax.swing.JTextArea TxbLink_procAutor;
    private javax.swing.JLabel TxbMax_Noticias;
    private javax.swing.JLabel TxbNumPublic_procAutor;
    private javax.swing.JLabel TxbNumero_Noticia;
    private javax.swing.JLabel TxbTipo_procAutor;
    private javax.swing.JLabel Txbmunicipio_area;
    private javax.swing.JLabel Txbmunicipio_brasao;
    private javax.swing.JLabel Txbmunicipio_email;
    private javax.swing.JLabel Txbmunicipio_habitante;
    private javax.swing.JLabel Txbmunicipio_nome;
    private javax.swing.JLabel Txbmunicipio_numfreg;
    private javax.swing.JLabel Txbmunicipio_presidente;
    private javax.swing.JLabel Txbmunicipio_site;
    private javax.swing.JLabel Txbmunicipio_tel;
    private javax.swing.JLabel Txt2;
    private javax.swing.JLabel Txt3;
    private javax.swing.JTextField Txt_AutorNoticia;
    private javax.swing.JTextField Txt_NomePresid;
    private javax.swing.JTextField Txt_TipoNoticia;
    private javax.swing.JComboBox<String> dropdia;
    private javax.swing.JComboBox<String> dropmes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblInv;
    private javax.swing.JLabel max_num_munic;
    private javax.swing.JLabel nomeNot_top1;
    private javax.swing.JLabel nomeNot_top2;
    private javax.swing.JLabel nomeNot_top3;
    private javax.swing.JLabel nomeNot_top4;
    private javax.swing.JLabel nomeNot_top5;
    private javax.swing.JLabel numNot_top1;
    private javax.swing.JLabel numNot_top2;
    private javax.swing.JLabel numNot_top3;
    private javax.swing.JLabel numNot_top4;
    private javax.swing.JLabel numNot_top5;
    private javax.swing.JLabel pesqCamPresidente_NoResult;
    private javax.swing.JLabel pesqCam_NoResult;
    private javax.swing.JTextField txt_NomeCamara;
    // End of variables declaration//GEN-END:variables
}
